//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerID { get; set; }
        public string contactPerson { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public decimal balance { get; set; }
        public string countryId { get; set; }
        public string countryName { get; set; }
    }
}
